apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-svc
  labels:
    app: feed-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-svc
  template:
    metadata:
      labels:
        app: feed-svc
    spec:
      containers:
      - name: feed-svc
        image: kdjordan/ud-project-udagram-microservices-users
        ports:
        - containerPort: 80