apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/user-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}